### ISSUE TITLE
devs will need to bump tycho version in pom

### ISSUE THREAD

**Issue by aaron-splicer** [buchen/bundled-jre#2]
simply cloning this project did not work.  got: java.lang.IllegalArgumentException: bundleLocation not found: /Users/aaronjevans/.m2/repository/org/eclipse/orbit/bundles/javax.annotation/1.3.5-SNAPSHOT/javax.annotation-1.3.5-SNAPSHOT.jar

Fix was to bump the tycho version because my primary tycho build was using v. 2.7.3, and apparently they are not compatible/causes confusion w/ maven.  So I simply had to bump tycho version to 2.7.3 in your root pom.

Thanks for this sample - was very helpful.

**Comment by buchen** [comment]
Is no using tycho 3.0.1
